title: Vicent Galiana, Sitecore and Azure
description: .Net, Sitecore and azure developer/architect
author: Vicent Galiana
github: https://github.com/galiana
about: I´m a Sitecore/.Net/Azure developer.
disqus_shortname: vicent-dev
google_analytics: UA-19087757-1

enableTags: true
tagarray: []
excerpt_separator: <!--more-->
collections:
  project:
    output: true
    permalink: /project/:path/
  posts:
    permalink: /post/:year/:month/:day/:title

social:
    - icon: fa-twitter
      link: "#"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/2332103/vicent-galiana"
      icon: fa-stack-exchange
    - link: "https://sitecore.stackexchange.com/users/151/vicent-galiana"
    - icon: fa-github
      link: "https://github.com/galiana"

share:
  twitter_username: vicent_galiana 

urls:
    - text: About Me
      url: /about/
    - text: VIcent Galiana CV
      url: /static/cv/Vicent Galiana CV 2019.pdf
    - text: XML Feed
      url: /feed.xml

url: "https://vicent.dev"
baseurl: ""
paginate: 20
per_page: 16
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
